// Created by iWeb 3.0.4 local-build-20140614

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id2" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="320" height="196" style="height: 196px; position: relative; width: 320px; " class="inline-block"><param name="src" value="../../Media/Post%20Lift%20-%201st%20Excursion%20-%20The%20Riverbed-medium.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}
else if(isiPhone)
{document.write('<object id="id2" type="video/quicktime" width="320" height="196" style="height: 196px; position: relative; width: 320px; " class="inline-block"><param name="src" value="Sunflower_Mine_Excursion_files/Post%20Lift%20-%201st%20Excursion%20-%20The%20Riverbed-medium-4.jpg"/><param name="target" value="myself"/><param name="href" value="../../../Media/Post%20Lift%20-%201st%20Excursion%20-%20The%20Riverbed-medium.m4v"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id2" type="video/quicktime" width="320" height="196" data="../../Media/Post%20Lift%20-%201st%20Excursion%20-%20The%20Riverbed-medium.m4v" style="height: 196px; position: relative; width: 320px; " class="inline-block"><param name="src" value="../../Media/Post%20Lift%20-%201st%20Excursion%20-%20The%20Riverbed-medium.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie2()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id6" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="320" height="197" style="height: 197px; left: 346px; position: absolute; top: 414px; width: 320px; z-index: 1; "><param name="src" value="../../Media/Post%20Lift%20-%201st%20Excursion%20-%20The%20Mine-mobile.m4v" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id6" type="video/quicktime" width="320" height="197" style="height: 197px; left: 346px; position: absolute; top: 414px; width: 320px; z-index: 1; "><param name="src" value="Sunflower_Mine_Excursion_files/Post%20Lift%20-%201st%20Excursion%20-%20The%20Mine-mobile-4.jpg"/><param name="target" value="myself"/><param name="href" value="../../../Media/Post%20Lift%20-%201st%20Excursion%20-%20The%20Mine-mobile.m4v"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id6" type="video/quicktime" width="320" height="197" data="../../Media/Post%20Lift%20-%201st%20Excursion%20-%20The%20Mine-mobile.m4v" style="height: 197px; left: 346px; position: absolute; top: 414px; width: 320px; z-index: 1; "><param name="src" value="../../Media/Post%20Lift%20-%201st%20Excursion%20-%20The%20Mine-mobile.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie3()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id11" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="320" height="196" style="height: 196px; position: relative; width: 320px; " class="inline-block"><param name="src" value="../../Media/Post%20Lift%20-%201st%20Excusion%20-%20The%20Crevice-medium.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}
else if(isiPhone)
{document.write('<object id="id11" type="video/quicktime" width="320" height="196" style="height: 196px; position: relative; width: 320px; " class="inline-block"><param name="src" value="Sunflower_Mine_Excursion_files/Post%20Lift%20-%201st%20Excusion%20-%20The%20Crevice-medium.jpg"/><param name="target" value="myself"/><param name="href" value="../../../Media/Post%20Lift%20-%201st%20Excusion%20-%20The%20Crevice-medium.m4v"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id11" type="video/quicktime" width="320" height="196" data="../../Media/Post%20Lift%20-%201st%20Excusion%20-%20The%20Crevice-medium.m4v" style="height: 196px; position: relative; width: 320px; " class="inline-block"><param name="src" value="../../Media/Post%20Lift%20-%201st%20Excusion%20-%20The%20Crevice-medium.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,379),url:'Sunflower_Mine_Excursion_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'Sunflower_Mine_Excursion_files/stroke_1.png'},{rect:new IWRect(2,-2,320,4),url:'Sunflower_Mine_Excursion_files/stroke_2.png'},{rect:new IWRect(322,-2,4,4),url:'Sunflower_Mine_Excursion_files/stroke_3.png'},{rect:new IWRect(322,2,4,379),url:'Sunflower_Mine_Excursion_files/stroke_4.png'},{rect:new IWRect(322,381,4,5),url:'Sunflower_Mine_Excursion_files/stroke_5.png'},{rect:new IWRect(2,381,320,5),url:'Sunflower_Mine_Excursion_files/stroke_6.png'},{rect:new IWRect(-2,381,4,5),url:'Sunflower_Mine_Excursion_files/stroke_7.png'}],new IWSize(324,383))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Sunflower_Mine_Excursion_files/Sunflower_Mine_ExcursionMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('../../Media/transparent.gif');fixupIECSS3Opacity('id13');applyEffects()}
function onPageUnload()
{Widget.onunload();}
